# Generated by Django 3.1.5 on 2021-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, upload_to='product_img'),
        ),
    ]
