# Generated by Django 3.1.5 on 2021-03-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingbasket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingbasketitems',
            old_name='basket_id',
            new_name='basket',
        ),
    ]
