# Generated by Django 3.1.5 on 2021-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, upload_to='product_img/'),
        ),
    ]
