# Generated by Django 3.1.5 on 2021-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_details',
            field=models.CharField(max_length=16),
        ),
    ]
